[package]
name = "rust-app"
version = "0.1.3"
edition = "2021"

[dependencies]
rust-argon2 = "1.0.0"
actix-web = "4"
rand = "0.8.5"
prometheus = "0.13.2"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
json = "0.12.4"
tokio-postgres = "0.7.7"
tokio = "1.21.2"
