---
global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
- job_name: go-app
  static_configs:
  - targets:
    - go-app:8080
- job_name: rust-app
  static_configs:
  - targets:
    - rust-app:8080
